behaviors:
  RobotAgent:
    trainer_type: sac
    hyperparameters:
      batch_size: 32
      buffer_size: 100000
      buffer_init_steps: 5000
      init_entcoef: 0.25
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1500000
    time_horizon: 256
    summary_freq: 50000
